#!/bin/bash

# Source the .env file so we have access to variables in this script
set -a
source .env
set +a

function wait_for(){
    attempts=0
    while ! eval $@ >/dev/null 2>&1; do
        if [[ $attempts -gt 99 ]] ; then
            echo "timed out waiting for $@"
            return 1
        fi
            attempts=$((attempts+1))
            sleep 3
    done
    return 0
}

#build dockerfile
echo "=> building containers" > /dev/stderr
dev/build

#bring up postgres container 
docker-compose -f dev/docker-compose.yaml up -d postgres

#wait for postgres container come up (Now uses the password from .env)
wait_for docker-compose -f dev/docker-compose.yaml exec -T -e PGPASSWORD=$POSTGRES_PASSWORD postgres psql -U postgres -d ecomm -c 'SELECT 1;'

#apply migration files
echo "=> applying migrations" > /dev/stderr
dev/migrate up

#bring up rest of the services 
echo "=> bringing up services" > /dev/stderr
docker-compose -f dev/docker-compose.yaml up -d